server:
  port: 7002

spring:
  application:
    name: microservicecloud-consumer-dept-7002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka/,http://localhost:81/eureka/,http://localhost:82/eureka/
feign:
  hystrix:
    enabled: true