spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-configserver-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-configserver-test